###服务启动端口号
server:
  port: 8081
###服务名称(服务注册到eureka名称)  
spring:
    application:
        name: app-clzblog-wechat
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8080/eureka
