server:
  port: 8081
spring:
  application:
    name: app-clzblog-wechat
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
swagger:
  base-package: site.clzblog.application.wechat.service
  title: "SpringCloud2.x build microservice wechat service interface"
  description: "This description"
  version: 0.0.1
  terms-of-service-url: https://www.clzblog.site
  contact:
    name: chengli.zou
    email: chengli.zou@gmail.com